---

extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  trailing-spaces: disable
  line-length:
    max: 180
  comments:
    require-starting-space: false
  truthy:
    allowed-values: ['true', 'false', 'on']
